# Development profile
spring:
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false

logging:
  level:
    com.bristol: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

bristol:
  bootstrap:
    demo-data: ${BOOTSTRAP_DEMO_DATA:true}
