INSERT INTO coupons (
    id,
    code,
    name,
    description,
    method,
    discount_type,
    value_type,
    value,
    schedule_type,
    start_date,
    end_date,
    status,
    minimum_requirement_type,
    minimum_purchase_amount,
    minimum_item_quantity,
    usage_limit_total,
    usage_limit_per_customer,
    times_used,
    is_customer_specific,
    applicable_product_category,
    applicable_product_subcategory,
    combine_with_product_discounts,
    created_at,
    updated_at,
    applies_to,
    selected_items,
    combine_with_order_discounts,
    combine_with_shipping_discounts,
    trigger_type,
    trigger_product_id,
    trigger_product_name,
    applies_to_future_orders,
    specific_customers,
    rule_config,
    priority,
    deleted_at
)
SELECT
    seed.id,
    seed.code,
    seed.name,
    seed.description,
    seed.method,
    seed.discount_type,
    seed.value_type,
    seed.value,
    seed.schedule_type,
    seed.start_date,
    seed.end_date,
    seed.status,
    seed.minimum_requirement_type,
    seed.minimum_purchase_amount,
    seed.minimum_item_quantity,
    seed.usage_limit_total,
    seed.usage_limit_per_customer,
    seed.times_used,
    seed.is_customer_specific,
    seed.applicable_product_category,
    seed.applicable_product_subcategory,
    seed.combine_with_product_discounts,
    seed.created_at,
    seed.updated_at,
    seed.applies_to,
    seed.selected_items,
    seed.combine_with_order_discounts,
    seed.combine_with_shipping_discounts,
    seed.trigger_type,
    seed.trigger_product_id,
    seed.trigger_product_name,
    seed.applies_to_future_orders,
    seed.specific_customers,
    seed.rule_config,
    seed.priority,
    NULL
FROM (
    VALUES
        (
            '2b7a1a45-3d65-4ef4-9e59-52a5bc8b4001'::uuid,
            NULL,
            '2x1 Six Pack Lager',
            'Promocion automatica 2x1 para el producto Six Pack Bristol Lager',
            'AUTOMATIC',
            'PRODUCT',
            'PERCENTAGE',
            100.00,
            'SCHEDULED',
            TIMESTAMP '2026-04-09 16:49:57.503871',
            NULL::timestamp,
            'ACTIVE',
            'NONE',
            NULL,
            NULL,
            NULL,
            NULL,
            0,
            FALSE,
            'ALL',
            'ALL',
            FALSE,
            TIMESTAMP '2026-04-10 16:49:57.503871',
            TIMESTAMP '2026-04-10 16:49:57.503871',
            'SPECIFIC_PRODUCTS',
            '[{"productId":"9c239e80-e51b-43cc-851b-bd5cfdcf5d59"}]',
            TRUE,
            TRUE,
            'NONE',
            NULL,
            NULL,
            FALSE,
            '[]',
            '{"type":"buy_x_for_y","buyX":2,"forY":1}',
            80
        ),
        (
            '7c1f0c9d-7bc5-4c06-8fcb-8b4d8e4f2002'::uuid,
            NULL,
            '10% Off Merchandising',
            'Promocion automatica del 10% sobre todos los productos de merchandising',
            'AUTOMATIC',
            'PRODUCT',
            'PERCENTAGE',
            10.00,
            'SCHEDULED',
            TIMESTAMP '2026-04-09 16:49:57.503871',
            NULL,
            'ACTIVE',
            'NONE',
            NULL,
            NULL,
            NULL,
            NULL,
            0,
            FALSE,
            'ALL',
            'ALL',
            FALSE,
            TIMESTAMP '2026-04-10 16:49:57.503871',
            TIMESTAMP '2026-04-10 16:49:57.503871',
            'SPECIFIC_PRODUCTS',
            '[{"category":"MERCHANDISING"}]',
            TRUE,
            TRUE,
            'NONE',
            NULL,
            NULL,
            FALSE,
            '[]',
            '{}',
            60
        ),
        (
            'd45a5c7c-6eb7-4c7c-a8a7-5f0d9d4b3003'::uuid,
            'DIST5ONA',
            '5% Distribuidor Ona',
            'Cupon del 5% para la distribuidora ona@mail.com',
            'CODE',
            'ORDER',
            'PERCENTAGE',
            5.00,
            'SCHEDULED',
            TIMESTAMP '2026-04-09 16:49:57.503871',
            NULL,
            'ACTIVE',
            'NONE',
            NULL,
            NULL,
            NULL,
            1,
            0,
            TRUE,
            'ALL',
            'ALL',
            TRUE,
            TIMESTAMP '2026-04-10 16:49:57.503871',
            TIMESTAMP '2026-04-10 16:49:57.503871',
            'ENTIRE_ORDER',
            '[]',
            FALSE,
            TRUE,
            'NONE',
            NULL,
            NULL,
            FALSE,
            '["ona@mail.com"]',
            '{}',
            70
        ),
        (
            '8d3dc5cf-7dc7-4c51-b4d7-9a91f4952c11'::uuid,
            NULL,
            '2x1 IPA',
            'Promocion automatica 2x1 para todos los productos IPA',
            'AUTOMATIC',
            'PRODUCT',
            'PERCENTAGE',
            100.00,
            'SCHEDULED',
            TIMESTAMP '2026-04-09 13:36:22.062682',
            NULL,
            'ACTIVE',
            'NONE',
            NULL,
            NULL,
            NULL,
            NULL,
            0,
            FALSE,
            'ALL',
            'ALL',
            FALSE,
            TIMESTAMP '2026-04-10 13:36:22.062682',
            TIMESTAMP '2026-04-10 13:36:22.062682',
            'SPECIFIC_PRODUCTS',
            '[{"beerType":"IPA"}]',
            TRUE,
            TRUE,
            'BUY_X_GET_Y',
            NULL,
            NULL,
            FALSE,
            '[]',
            '{"buyX":2,"getY":1}',
            50
        )
) AS seed(
    id,
    code,
    name,
    description,
    method,
    discount_type,
    value_type,
    value,
    schedule_type,
    start_date,
    end_date,
    status,
    minimum_requirement_type,
    minimum_purchase_amount,
    minimum_item_quantity,
    usage_limit_total,
    usage_limit_per_customer,
    times_used,
    is_customer_specific,
    applicable_product_category,
    applicable_product_subcategory,
    combine_with_product_discounts,
    created_at,
    updated_at,
    applies_to,
    selected_items,
    combine_with_order_discounts,
    combine_with_shipping_discounts,
    trigger_type,
    trigger_product_id,
    trigger_product_name,
    applies_to_future_orders,
    specific_customers,
    rule_config,
    priority
)
WHERE NOT EXISTS (
    SELECT 1
    FROM coupons c
    WHERE c.id = seed.id
);
